---

# - name: Reload systemd
  # systemd:
    # daemon_reload: yes

# - name: Restart kafka-manager service
  # service:
    # name: kafka-manager
    # state: restarted

- name: start kafka-manager
  #shell: '{{ kafka_manager_dir }}/bin/kafka-manager-start.sh'
  shell: 'nohup {{ kafka_manager_dir }}/bin/kafka-manager -Dconfig.file={{ kafka_manager_dir }}/conf/application.conf -Dapplication.home={{ kafka_manager_dir }} >/dev/null 2>&1&'

- name: stop kafka-manager
  shell: '{{ kafka_manager_dir }}/bin/kafka-manager-stop.sh'
