---

# - name: Reload systemd
  # systemd:
    # daemon_reload: yes

# - name: Restart kafka-manager service
  # service:
    # name: kafka-manager
    # state: restarted

- name: start kafka-manager
  shell: '{{ kafka_manager_dir }}/bin/kafka-manager-start.sh'

- name: stop kafka-manager
  shell: '{{ kafka_manager_dir }}/bin/kafka-manager-stop.sh'
